services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: fintech_msa_db
    ports:
      - "3700:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fintech

  auth-server:
    build: ./backend/auth_server
    container_name: auth_server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - fintech

  business-server:
    build: ./backend/business_server
    container_name: business_server
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - fintech

  payment-server:
    build: ./backend/payment_server
    container_name: payment_server
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - fintech

  ai-server:
    build: ./backend/ai_server
    container_name: ai_server
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - fintech

  frontend:
    build: ./frontend/react
    container_name: front
    ports:
      - "5173:5173"
    networks:
      - fintech

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fintech

  nginx:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "80:80"
    depends_on:
      - auth-server
      - business-server
      - payment-server
      - ai-server
      - redis
    networks:
      - fintech

volumes:
  mysql_data:

networks:
  fintech:
    driver: bridge

# docker rmi -f $(docker images -q) - 모든이미지 삭제
# docker rm $(docker ps -aq) - 모든 컨테이너 삭제
# docker network prune -f - 기본 네트워크 제외 모든 네트워크 삭제
# docker-compose up -d --build -  빌드 후 실행
# docker-compose down - 실행중지