apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
        - name: ai-server
          image: msa_project/ai-server:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-key
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: db-password
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server
spec:
  type: ClusterIP
  selector:
    app: ai-server
  ports:
    - port: 8083
      targetPort: 8083
