apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-server
  template:
    metadata:
      labels:
        app: payment-server
    spec:
      containers:
        - name: payment-server
          image: msa_project/payment-server:latest
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: jwt-key
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: db-password
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-server
spec:
  type: ClusterIP
  selector:
    app: payment-server
  ports:
    - port: 8082
      targetPort: 8082
