apiVersion: v1  # API 버전 명시
kind: Secret  # 리소스 유형 명시
metadata:
  name: global-secrets  # Secret 이름
type: Opaque  # Secret의 기본 타입 (Key-Value 쌍 저장)
data:
  db-user: bXlzcWx1c2Vy     # base64 인코딩된 'mysqluser'
  db-password: bXlzcWxwYXNz  # base64 인코딩된 'mysqlpass'
  jwt-key: bXlfanZ0X3NlY3JldA==  # base64 인코딩된 'my_jwt_secret'
