spring:
  application:
    name: payment_server

  datasource:
    url: jdbc:mysql://mysql:3306/fintech_msa_db
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis
#      host: localhost
      port: 6379

#http://localhost:9091/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true

server:
  port: 8082